import "../styles/globals.css"; // Đảm bảo đường dẫn đúng

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="pt-20">
        <header className="fixed top-0 left-0 w-full bg-lightblue py-5 px-10 flex items-center justify-between z-50">
          {/* Logo */}
          <h2 className="text-2xl font-bold">SigmaRizzler Hotel</h2>

          {/* Navigation - Đẩy về bên phải */}
          <nav className="flex gap-6 items-center ml-auto">
            <a href="#" className="text-lg hover:text-blue-600">
              Trang chủ
            </a>
            <a href="#" className="text-lg hover:text-blue-600">
              Về chúng tôi
            </a>
            <a href="#" className="text-lg hover:text-blue-600">
              Các dịch vụ
            </a>
            <a href="#" className="text-lg hover:text-blue-600">
              Liên hệ
            </a>
            <button className="bg-blue-500 text-white px-4 py-2 rounded-lg hover:bg-blue-700 transition">
              Đăng nhập
            </button>
          </nav>
        </header>
        {children}
        <footer
          style={{
            backgroundColor: "ghostwhite",
            padding: "1rem",
          }}
        >
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
