version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: no
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotel_booking
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3320:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_service
    restart: no
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: hotel_booking

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frontend_service
    restart: no
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:5000

volumes:
  mysql_data:
