export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function AuthLayout({ children }) {
  return (
    <html>
      <body>
        <div className="flex min-h-screen items-center justify-center bg-gray-100">
          <div className="w-full max-w-md bg-white p-6 rounded-lg shadow-md">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}

